version: '3.3'

services:


  postgres:
    image: postgres:11.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/postgresql/:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U username -d database" ]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    restart: on-failure
    build:
      context: .
    command: [ "/todo"]
    ports:
      - 80:80
    depends_on:
      - postgres
    links:
      - postgres
    env_file:
      - .env
    environment:
      DATABASE_HOST: postgres
    container_name: todo-server